version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    build: './docker/php'
    volumes:
      - ./public:/var/www/html
      
  rabbitmq:
      image: rabbitmq:3.8.2-management
      container_name: rabbitmq
      volumes:
        - ./docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
      #environment:
      #    RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      #    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      #    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      ports:
          - 15672:15672