version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./:/app
