version: "3.7"

services:
  nginx:
    image: nginx
    working_dir: /var/www/html
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT:-6379}:6379

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
    links:
      - redis

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./docker/data/db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    links:
      - php-fpm
