version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./public:/var/www/html
