version: "3.7"

services:
  nginx:
    build: docker/nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - .:/var/www/html
      - ./docker/data/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/data/nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
