version: "3.7"

services:
  nginx:
    image: nginx
    working_dir: /var/www/html
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
